/**
 * `airlock build` — build a reproducible, per-project Docker image for a Worker
 * (epic 09, ADR-0012). This is the answer to "different Python/versions per machine":
 * the image pins the base runtime + the operator's tool code + their `requirements.txt`.
 *
 * Flow: validate worker.yaml through the one schema (C2 gate) → generate a Dockerfile
 * `FROM airlockhq/airlock` that COPYs the project and pip-installs requirements → tag the
 * image by a CONTENT HASH of (worker.yaml + requirements.txt) so the same manifest yields
 * the same tag (the epic-08 version artifact) → `docker build`.
 */

import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { parse as parseYaml } from 'yaml';

import { inheritSpawner, type Spawner } from '../exec.js';
import { validateWorker } from '../worker-schema/validate.js';

export const DEFAULT_BASE_IMAGE = 'airlockhq/airlock:dev';

export interface BuildOptions {
  cwd?: string;
  /** Base image to layer on (default airlockhq/airlock:dev). */
  base?: string;
  /** Skip building the base image even if it's absent locally. */
  noBaseBuild?: boolean;
  spawnImpl?: Spawner;
}

export interface BuildPlan {
  image: string; // airlock/<name>:<tag>
  tag: string; // content hash
  base: string;
  dockerfile: string; // generated Dockerfile text
  contextDir: string; // docker build context (the project dir)
  hasRequirements: boolean;
}

/** Slugify a worker name into a docker-safe repo segment. */
export function slug(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9_.-]+/g, '-')
      .replace(/^-+|-+$/g, '') || 'worker'
  );
}

/** Content-addressed tag: same manifest (+ requirements) ⇒ same image (epic 08). */
export function computeTag(parts: Array<string | Buffer>): string {
  const h = createHash('sha256');
  for (const p of parts) h.update(p);
  return h.digest('hex').slice(0, 12);
}

/** The generated per-project Dockerfile. Pure + testable. */
export function generateDockerfile(base: string, hasRequirements: boolean): string {
  const lines = [
    `# Generated by \`airlock build\` — reproducible per-project Worker image (ADR-0012).`,
    `FROM ${base}`,
    `COPY . /app/worker`,
  ];
  if (hasRequirements) {
    lines.push(`RUN pip install --no-cache-dir -r /app/worker/requirements.txt`);
  }
  lines.push(`WORKDIR /app/worker`, `# the runtime reads ./worker.yaml from here`, '');
  return lines.join('\n');
}

/** Resolve everything needed to build, without invoking docker. Pure-ish (reads files). */
export function resolveBuildPlan(opts: BuildOptions = {}): BuildPlan {
  const cwd = opts.cwd ?? process.cwd();
  const workerPath = resolve(cwd, 'worker.yaml');
  if (!existsSync(workerPath)) {
    throw new Error(`no worker.yaml in ${cwd} — run \`airlock init\` or \`airlock migrate\` first.`);
  }
  const workerBytes = readFileSync(workerPath);
  const manifest = parseYaml(workerBytes.toString());

  // C2 gate: the CLI validates; the runtime then trusts.
  const { ok, errors } = validateWorker(manifest);
  if (!ok) {
    throw new Error(`worker.yaml is invalid (fix before building):\n  - ${errors.join('\n  - ')}`);
  }

  const reqPath = resolve(cwd, 'requirements.txt');
  const hasRequirements = existsSync(reqPath);
  const reqBytes = hasRequirements ? readFileSync(reqPath) : Buffer.from('');
  const base = opts.base ?? DEFAULT_BASE_IMAGE;

  const name = slug(manifest?.worker?.name ?? 'worker');
  const tag = computeTag([workerBytes, reqBytes, base]);
  return {
    image: `airlock/${name}:${tag}`,
    tag,
    base,
    dockerfile: generateDockerfile(base, hasRequirements),
    contextDir: cwd,
    hasRequirements,
  };
}

/** Locate the runtime source dir (for building the base image in the monorepo). */
function runtimeDir(): string {
  // packages/cli/src/commands/build.ts → repo/python/agent-runtime
  const here = dirname(fileURLToPath(import.meta.url));
  return resolve(here, '../../../../python/agent-runtime');
}

export interface BuildResult extends BuildPlan {
  dockerfilePath: string;
}

export async function runBuild(opts: BuildOptions = {}): Promise<BuildResult> {
  const plan = resolveBuildPlan(opts);
  const spawn = opts.spawnImpl ?? inheritSpawner;

  // Ensure the base image exists locally (monorepo dev). `--no-base-build` skips.
  if (!opts.noBaseBuild && plan.base === DEFAULT_BASE_IMAGE) {
    const rt = runtimeDir();
    if (existsSync(join(rt, 'Dockerfile'))) {
      console.log(`airlock build  →  ensuring base image ${plan.base}…`);
      await spawn('docker', ['build', '-t', plan.base, rt], rt);
    }
  }

  const dockerfilePath = join(tmpdir(), `airlock.Dockerfile.${plan.tag}`);
  writeFileSync(dockerfilePath, plan.dockerfile);

  console.log(`airlock build  →  ${plan.image}  (context: ${plan.contextDir})`);
  const code = await spawn(
    'docker',
    ['build', '-f', dockerfilePath, '-t', plan.image, plan.contextDir],
    plan.contextDir,
  );
  if (code !== 0) throw new Error(`docker build failed (exit ${code})`);
  console.log(`\n✓ built ${plan.image}`);
  console.log(`  run it:  airlock up --docker --image ${plan.image}`);
  return { ...plan, dockerfilePath };
}
