/**
 * `airlock up` — run a self-hosted agent on the publisher's OWN hardware and
 * front it with a public URL. This is the self-host production path: the agent
 * loop (`python -m airlock_agent`) runs here, and airlock only operates the
 * tunnel that exposes it — never the compute, never the model (which may be
 * local or a remote OPENAI_API_BASE).
 *
 * Public startup uses the saved Caddy + frp relay profile.
 * Pass --no-tunnel for explicit local development.
 */

import { type ChildProcess, spawn, spawnSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { readRelayConfig } from '../relay-config.js';
import { startRelay, type RelayHandle } from '../relay.js';
import type { ManagedAccess } from '../managed-access.js';
import { existsSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { buildDockerRun } from '../exec.js';
import { DEFAULT_BASE_IMAGE, resolveBuildPlan } from './build.js';
import { type AirlockConfig, readConfig } from '../config-file.js';

export interface UpOptions {
  cwd?: string;
  /** Port the agent listens on (and we tunnel to). */
  port?: number;
  /** Python executable to run `-m airlock_agent` with (respects an active venv). */
  python?: string;
  /** Run the agent locally but don't open a public tunnel. */
  noTunnel?: boolean;
  /** Saved native relay profile; defaults to .airlock/relay.json. */
  relay?: string;
  startRelayImpl?: typeof startRelay;
  /** Generated by the trusted local launcher, never entered in the worker UI. */
  access?: ManagedAccess;
  /** Max agent runs in flight at once before callers queue (AIRLOCK_MAX_CONCURRENCY). */
  maxConcurrency?: number;
  /** Max callers waiting beyond the running set before new ones get 429 (AIRLOCK_MAX_QUEUE). */
  maxQueue?: number;
  /** Seconds a caller waits in the queue before a 429 (AIRLOCK_QUEUE_TIMEOUT_S). */
  queueTimeout?: number;
  /** Force per-call agent rebuild on/off (AIRLOCK_BUILD_PER_CALL); default inferred at runtime. */
  buildPerCall?: boolean;
  /** Run the Worker in Docker (reproducible) instead of host python (ADR-0012). */
  docker?: boolean;
  /** Image to run with --docker (default: the content-addressed image from `airlock build`). */
  image?: string;
  /** Dev mode: mount the project into the base image instead of using a built image. */
  mount?: boolean;
  /** Path passed to `docker run --env-file` (secrets). */
  envFile?: string;
  /** Variant/profile to run (sets AIRLOCK_PROFILE) — e.g. internal | external. */
  profile?: string;
  /** Injectables for tests. */
  spawnImpl?: typeof spawn;
  fetchImpl?: typeof fetch;
}

export interface UpPlan {
  python: string;
  args: string[];
  port: number;
  /** Env overlay handed to the agent process (merged over process.env at spawn). */
  env: Record<string, string>;
}

/**
 * Translate config + options into a concrete launch plan. Pure + testable.
 * Throws if there's no `[agent]` block — `up` runs a config-bound harness.
 */
export function resolveUpPlan(config: AirlockConfig, opts: UpOptions = {}): UpPlan {
  // The redesign runtime boots from worker.yaml (epic 07): if one is present, `up`
  // just spawns it — the worker.yaml supplies harness/entrypoint/tools/models. The
  // legacy [agent] block is still accepted during the deprecation window.
  const cwd = opts.cwd ?? process.cwd();
  const hasWorkerYaml = existsSync(resolve(cwd, 'worker.yaml'));
  if (!config.agent?.entrypoint && !hasWorkerYaml) {
    throw new Error(
      'airlock up needs a worker.yaml (run `airlock init` or `airlock migrate`), ' +
        'or a legacy [agent] block in .airlock/config.toml (`airlock init --detect`).',
    );
  }
  const port = opts.port ?? 3000;
  const env: Record<string, string> = { PORT: String(port) };

  // Concurrency knobs — only set when given, so the runtime keeps its own
  // defaults otherwise. A bare `AIRLOCK_MAX_CONCURRENCY=N airlock up` also works
  // because the spawned process inherits process.env.
  if (opts.maxConcurrency !== undefined) env.AIRLOCK_MAX_CONCURRENCY = String(opts.maxConcurrency);
  if (opts.maxQueue !== undefined) env.AIRLOCK_MAX_QUEUE = String(opts.maxQueue);
  if (opts.queueTimeout !== undefined) env.AIRLOCK_QUEUE_TIMEOUT_S = String(opts.queueTimeout);
  if (opts.buildPerCall !== undefined) env.AIRLOCK_BUILD_PER_CALL = opts.buildPerCall ? '1' : '0';

  return {
    python: opts.python ?? process.env.AIRLOCK_PYTHON ?? 'python3',
    args: ['-m', 'airlock_agent'],
    port,
    env,
  };
}

export interface UpHandle {
  /** The public URL, if a tunnel was opened. */
  url?: string;
  /** Stop the tunnel and the agent process. */
  stop: () => Promise<void>;
  /** Resolves when the agent process exits. */
  done: Promise<number>;
}

/** Poll the agent's /healthz until it responds or we give up. */
async function waitForHealth(
  port: number,
  fetchFn: typeof fetch,
  child: ChildProcess,
  timeoutMs: number,
): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (child.exitCode !== null) {
      throw new Error(`agent exited (code ${child.exitCode}) before becoming healthy`);
    }
    try {
      const res = await fetchFn(`http://localhost:${port}/healthz`);
      if (res.ok) return;
    } catch {
      // not up yet
    }
    await new Promise((r) => setTimeout(r, 500));
  }
  throw new Error(
    `agent did not become healthy on :${port} within ${Math.round(timeoutMs / 1000)}s`,
  );
}

/**
 * Launch the agent + tunnel and return a handle. The caller wires signal
 * handling (see the `up` command in cli.ts). The model is whatever the agent's
 * own code points at — local weights or a remote OPENAI_API_BASE in the env,
 * which the spawned process inherits.
 */
export async function runUp(opts: UpOptions = {}): Promise<UpHandle> {
  const cwd = opts.cwd ?? process.cwd();
  const noTunnel = opts.noTunnel ?? false;
  const relay = noTunnel ? null : await readRelayConfig(resolve(cwd, opts.relay ?? '.airlock/relay.json'));
  const instance = randomUUID();
  if (relay && (!(opts.access?.operator || process.env.AIRLOCK_OPERATOR_TOKEN) || !/^[a-f0-9]{64}$/i.test(process.env.AIRLOCK_RELAY_TOKEN ?? ''))) {
    throw new Error('public startup requires AIRLOCK_OPERATOR_TOKEN and a 64-character hex AIRLOCK_RELAY_TOKEN');
  }
  // worker.yaml-only projects have no .airlock/config.toml — tolerate its absence
  // and fall back to a minimal config (the runtime reads worker.yaml itself).
  let config: AirlockConfig;
  try {
    config = await readConfig(cwd);
  } catch (err) {
    if (!existsSync(resolve(cwd, 'worker.yaml'))) throw err;
    config = { project: { name: 'worker' } } as AirlockConfig;
  }
  const spawnFn = opts.spawnImpl ?? spawn;
  const fetchFn = opts.fetchImpl ?? fetch;

  const port = opts.port ?? 3000;
  let containerName: string | undefined;
  let binary: string;
  let args: string[];
  let spawnEnv: Record<string, string> = { ...process.env } as Record<string, string>;

  if (opts.docker) {
    // Reproducible containerized run (ADR-0012): publish the port, mount the state
    // volume so the SQLite store persists, wire host.docker.internal for host models.
    const stateDir = resolve(cwd, '.airlock');
    mkdirSync(stateDir, { recursive: true });
    let image = opts.image;
    let mountDir: string | undefined;
    if (opts.mount) {
      image = image ?? DEFAULT_BASE_IMAGE;
      mountDir = cwd; // dev: mount the project; no rebuild
    } else if (!image) {
      image = resolveBuildPlan({ cwd }).image; // the content-addressed image from `airlock build`
    }
    // Include the port so several workers can run side by side (worker.yaml projects
    // share the default config name, so the name alone isn't unique).
    containerName = `airlock-${slug(config.project?.name ?? 'worker')}-${port}`;
    const dockerEnv = forwardedEnv();
    if (opts.access) {
      dockerEnv.AIRLOCK_OPERATOR_TOKEN = opts.access.operator;
      dockerEnv.AIRLOCK_MANAGED_CALLER_KEY = opts.access.caller;
    }
    if (relay) dockerEnv.AIRLOCK_PUBLIC_INSTANCE = instance;
    if (opts.profile) dockerEnv.AIRLOCK_PROFILE = opts.profile;
    const run = buildDockerRun({
      image: image!,
      port,
      publishHost: '127.0.0.1',
      name: containerName,
      stateDir,
      mountDir,
      addHostGateway: true,
      envFile: opts.envFile,
      env: dockerEnv,
    });
    binary = run.binary;
    args = run.args;
    console.log(`airlock up  →  docker run ${image} (:${port})`);
  } else {
    const plan = resolveUpPlan(config, opts);
    binary = plan.python;
    args = plan.args;
    spawnEnv = { ...process.env, ...plan.env } as Record<string, string>;
    if (opts.profile) spawnEnv.AIRLOCK_PROFILE = opts.profile;
    console.log(`airlock up  →  starting agent: ${plan.python} -m airlock_agent (:${plan.port})`);
  }

  if (opts.access) {
    spawnEnv.AIRLOCK_OPERATOR_TOKEN = opts.access.operator;
    spawnEnv.AIRLOCK_MANAGED_CALLER_KEY = opts.access.caller;
  }
  if (relay) spawnEnv.AIRLOCK_PUBLIC_INSTANCE = instance;
  if (!opts.docker) spawnEnv.AIRLOCK_HOST = '127.0.0.1';
  const child = spawnFn(binary, args, { cwd, stdio: 'inherit', env: spawnEnv, windowsHide: true });

  const workerDone = new Promise<number>((resolve) => {
    child.on('exit', (code) => resolve(code ?? 0));
    child.on('error', () => resolve(1));
  });

  let tunnel: RelayHandle | undefined;
  try {
    await waitForHealth(port, fetchFn, child, 120_000);
    if (relay) {
      const authCheck = await fetchFn(`http://127.0.0.1:${port}/v1/jobs/airlock-auth-probe`, {
        redirect: 'error', signal: AbortSignal.timeout(3000),
      });
      if (authCheck.status !== 401) throw new Error('public worker must reject unauthenticated job access with 401');
      console.log('  connecting to your Caddy relay…');
      tunnel = await (opts.startRelayImpl ?? startRelay)(port, { config: relay, instance });
    }
  } catch (err) {
    tunnel?.stop();
    child.kill();
    if (containerName) spawnSync('docker', ['stop', containerName]);
    throw err;
  }

  if (tunnel) {
    console.log(`\n✓ public worker verified at  ${tunnel.url}`);
    console.log(`  console:      ${tunnel.url}/console`);
    console.log(`  callers POST to:  ${tunnel.url}/v1/chat/completions`);
  } else {
    console.log(`\n✓ worker ready on port ${port} (no tunnel)`);
    console.log(`  local:        http://localhost:${port}/v1/chat/completions`);
  }
  console.log('  press Ctrl-C to stop');

  const done = tunnel ? Promise.race([
    workerDone.then((code) => { tunnel!.stop(); return code; }),
    tunnel.done.then(() => {
      child.kill();
      if (containerName) spawnSync('docker', ['stop', containerName]);
      return 1; // Losing the connector must never look like a successful service exit.
    }),
  ]) : workerDone;

  return {
    url: tunnel?.url,
    stop: async () => {
      tunnel?.stop();
      child.kill();
      if (containerName) spawnSync('docker', ['stop', containerName]);
      await workerDone;
    },
    done,
  };
}

/** Forward a small allowlist of host env into the container (secrets + knobs). */
function forwardedEnv(): Record<string, string> {
  const env: Record<string, string> = {};
  const allow = ['HOOK_SECRET', 'OPENAI_API_KEY', 'OPENAI_API_BASE'];
  for (const k of Object.keys(process.env)) {
    if (allow.includes(k) || k.startsWith('AIRLOCK_')) {
      const v = process.env[k];
      if (v !== undefined) env[k] = v;
    }
  }
  return env;
}

function slug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9_.-]+/g, '-').replace(/^-+|-+$/g, '') || 'worker';
}
