export const styles = String.raw`
:root{color-scheme:light;--paper:#f5f4f0;--surface:#fffefa;--ink:#24342f;--muted:#65706a;--line:#dddeda;--green:#21664b;--soft:#e8eee6;--danger:#a54132;font-family:Inter,"Segoe UI",system-ui,sans-serif;font-size:15px}
*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink)}button,input,select{font:inherit}button,a,input,select{-webkit-tap-highlight-color:transparent}
button{cursor:pointer}button:disabled{cursor:default;opacity:.5}a{color:inherit}button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible,summary:focus-visible{outline:3px solid #a3bb80;outline-offset:4px}
.shell{max-width:1160px;margin:auto;padding:0 42px}header{height:100px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line)}
.brand{display:flex;align-items:center;gap:12px;font-size:23px;font-weight:650;letter-spacing:-1px}.mark{display:grid;place-items:center;width:31px;height:35px;background:var(--green);border-radius:15px 15px 5px 5px;color:white;font-size:18px}
.machine{font-size:12px;color:var(--muted);display:flex;gap:9px;align-items:center}.dot{width:7px;height:7px;border-radius:50%;background:#638c65}
main{padding:52px 0 70px}.eyebrow{font-size:11px;font-weight:650;letter-spacing:1.7px;text-transform:uppercase;color:var(--muted)}h1{font-weight:500;font-size:38px;letter-spacing:-1.4px;line-height:1.12;margin:12px 0}p{line-height:1.6}.intro{margin:0;color:var(--muted);max-width:560px}
.workspace{display:grid;grid-template-columns:1fr 1.05fr;min-height:390px;margin-top:36px;border:1px solid var(--line);border-radius:18px;background:var(--surface);overflow:hidden}
.selection{padding:32px;border-right:1px solid var(--line)}.field-label{display:block;font-size:12px;font-weight:650;margin:24px 0 9px}.field-label:first-child{margin-top:0}
select,input{width:100%;border:1px solid var(--line);border-radius:9px;background:var(--surface);color:var(--ink);padding:13px 12px;min-height:48px}select{cursor:pointer}
.agent-path{color:var(--muted);font-size:12px;word-break:break-word;min-height:34px;margin:10px 0 23px}.framework-note{font-size:12px;color:var(--muted);margin:8px 0 0}
.primary{background:var(--green);border:1px solid var(--green);color:#fff;min-height:48px;border-radius:9px;padding:12px 20px;font-weight:600;transition:background .16s,transform .16s}.primary:hover{background:#194f3b}.primary:active{transform:translateY(1px)}.wide{width:100%;margin-top:26px}
.secondary{border:1px solid var(--line);background:var(--surface);padding:11px 16px;border-radius:9px;min-height:44px}.secondary:hover{background:var(--soft)}.quiet{border:0;background:transparent;color:var(--muted);padding:10px 0;text-decoration:underline;text-underline-offset:4px;font-size:12px}.quiet:hover{color:var(--ink)}
.connection{padding:32px;display:flex;flex-direction:column;background:#eeefe9}.status{display:flex;align-items:center;gap:8px;font-size:12px;color:var(--muted)}.status i{height:7px;width:7px;background:#8a938b;border-radius:50%}.status[data-state=running] i{background:var(--green)}
.link-symbol{width:55px;height:55px;border:1px solid #cbd3c8;border-radius:50%;display:grid;place-items:center;color:#59715c;margin-top:37px}.link-symbol svg{width:24px;height:24px}
h2{font-weight:500;font-size:25px;letter-spacing:-.7px;margin:18px 0 4px}.connection p{font-size:13px;color:var(--muted);margin:4px 0 18px;max-width:320px}.url{font-family:ui-monospace,monospace;font-size:13px;background:#fffefa;border:1px solid var(--line);padding:13px;border-radius:8px;overflow-wrap:anywhere}
.actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:14px}.actions a{text-decoration:none}.connection-bottom{margin-top:auto;padding-top:24px;font-size:11px;color:var(--muted)}
.notice{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:20px 0;border-bottom:1px solid var(--line);font-size:13px}.notice p{margin:0;color:var(--muted)}.notice strong{font-weight:550;color:var(--ink)}
details{margin-top:22px}summary{font-size:12px;color:var(--muted);cursor:pointer;width:fit-content}.settings{padding:18px 0;max-width:610px}.settings p{font-size:13px;color:var(--muted);margin-top:0}.settings .row{display:flex;gap:10px;align-items:center}.settings input{flex:1}
.error{color:var(--danger);font-size:13px;margin:16px 0 0;white-space:pre-wrap;overflow-wrap:anywhere}.footer{display:flex;justify-content:space-between;margin-top:28px;font-size:11px;color:var(--muted)}.hidden,[hidden]{display:none!important}
.gateway-checks{list-style:none;padding:0;margin:22px 0}.gateway-checks li{border-top:1px solid var(--line);padding:16px 0}.gateway-checks strong{font-size:13px;font-weight:600}.gateway-checks p{margin:6px 0 0;overflow-wrap:anywhere}#gatewayMessage{margin-top:16px}#addressHelp{margin-top:9px;font-size:12px}.settings h2{margin:0 0 12px}.settings details p{margin-top:16px}
@media(max-width:720px){.shell{padding:0 22px}header{height:76px}main{padding:32px 0}h1{font-size:32px}.workspace{grid-template-columns:1fr;margin-top:26px}.selection{border-right:0;border-bottom:1px solid var(--line);padding:24px}.connection{padding:24px;min-height:305px}.link-symbol{margin-top:24px}.notice{align-items:flex-start}.settings .row{flex-wrap:wrap}.settings input{flex-basis:100%}.machine{font-size:11px}.footer{gap:12px}}
@media(prefers-reduced-motion:reduce){*{transition:none!important;scroll-behavior:auto!important}}
`;
