/**
 * `airlock migrate` — scaffold a `worker.yaml` from a legacy
 * `.airlock/config.toml`.
 *
 * `worker.yaml` is the single operational manifest of the redesign (epic 07).
 * This is a STUB: it maps the fields that exist today (project / agent / tunnel);
 * any legacy block it does not recognize is simply not carried over. The
 * remaining manifest blocks (controls, routing, fallback, io, state, sessions,
 * cache, triggers, auth/tenancy, pricing, sandbox) are emitted as commented TODO
 * placeholders and get their real schema in epic 07. A hand-rolled emitter is
 * used on purpose so this stub adds no new dependency; epic 07 replaces it with
 * the real loader/serializer.
 */

import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { type AirlockConfig, readConfig, validateTunnel } from './config-file.js';

export interface MigrateOptions {
  cwd?: string;
  /** Output filename relative to cwd (default `worker.yaml`). */
  out?: string;
}

export interface MigrateResult {
  workerPath: string;
  yaml: string;
}

/** Quote a scalar for YAML (double-quoted, with the few needed escapes). */
function q(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

/**
 * Render a `worker.yaml` body from a legacy config. Pure + testable. Maps:
 *   [project].name        → worker.name
 *   [agent].harness/...   → harness / entrypoint
 *   [tunnel].durable      → expose (public when durable, else internal)
 * Unrecognized legacy blocks are intentionally not carried over.
 */
export function configToWorkerYaml(config: AirlockConfig): string {
  const lines: string[] = [];
  lines.push('# Generated by `airlock migrate` from .airlock/config.toml.');
  lines.push('# worker.yaml is the single operational manifest (redesign epic 07). This stub');
  lines.push('# maps the legacy project/agent/tunnel fields; the remaining blocks are');
  lines.push('# scaffolded as TODOs and defined in epic 07.');
  lines.push('schemaVersion: 1');
  lines.push('');
  lines.push('worker:');
  lines.push(`  name: ${q(config.project.name)}`);
  if (config.project.mode) lines.push(`  mode: ${q(config.project.mode)}`);

  if (config.agent) {
    lines.push('');
    lines.push('# A skill is a callable; the harness contributes tools/planner/prompt and the');
    lines.push('# loop engine drives it (epic 01).');
    lines.push(`harness: ${q(config.agent.harness)}`);
    lines.push(`entrypoint: ${q(config.agent.entrypoint)}`);
    if (config.agent.build_per_call !== undefined) {
      lines.push(`build_per_call: ${config.agent.build_per_call}`);
    }
    // A default model binding so the migrated worker boots; add named bindings for
    // mid-run routing/fallback (epic 03).
    lines.push('');
    lines.push('models:');
    lines.push('  default: {}');
  }

  // Tunnel → expose. A durable named tunnel maps to public reach; otherwise the
  // worker stays internal (epic 09 owns the full expose/fleet-router model).
  const tunnel = validateTunnel(config);
  lines.push('');
  lines.push(`expose: ${tunnel?.durable ? 'public' : 'internal'}`);
  if (tunnel) {
    lines.push('tunnel:');
    if (tunnel.hostname) lines.push(`  hostname: ${q(tunnel.hostname)}`);
    if (tunnel.protocol) lines.push(`  protocol: ${q(tunnel.protocol)}`);
    if (tunnel.region) lines.push(`  region: ${q(tunnel.region)}`);
    if (tunnel.metrics) lines.push(`  metrics: ${q(tunnel.metrics)}`);
  }

  lines.push('');
  lines.push('# Optional blocks (see worker.schema.json for the full set):');
  lines.push('#   controls:  { max_steps: 50, budget: { tokens: 100000 } }   # guards/approval (epic 02)');
  lines.push('#   routing:   { default: default, by_role: { quick: fast } }  # mid-run model routing (epic 03)');
  lines.push('#   state:     { backend: sqlite }                             # checkpoint/cache (epic 04)');
  lines.push('#   io:        { input_guards: [{}], output: { format: json } } # contract shaping (epic 13)');
  lines.push('#   auth:      { scheme: api_key }                             # multi-tenancy (epic 10)');
  lines.push('#   sandbox:   { enabled: true }                               # tool isolation (epic 06)');
  lines.push('');
  return lines.join('\n');
}

/** The object form of a migrated manifest — used to validate against the one schema (C2). */
export function configToWorkerObject(config: AirlockConfig): Record<string, unknown> {
  const tunnel = validateTunnel(config);
  const obj: Record<string, unknown> = {
    worker: { name: config.project.name },
    harness: config.agent?.harness ?? 'stub',
    expose: tunnel?.durable ? 'public' : 'internal',
    models: { default: {} },
  };
  if (config.agent?.entrypoint) obj.entrypoint = config.agent.entrypoint;
  return obj;
}

export async function runMigrate(opts: MigrateOptions = {}): Promise<MigrateResult> {
  const cwd = opts.cwd ?? process.cwd();
  const config = await readConfig(cwd);
  const yaml = configToWorkerYaml(config);
  // C2: every producer of a worker.yaml routes through the one validator.
  const { validateWorker } = await import('./worker-schema/validate.js');
  const { ok, errors } = validateWorker(configToWorkerObject(config));
  if (!ok) {
    throw new Error(`migration produced an invalid worker.yaml:\n  - ${errors.join('\n  - ')}`);
  }
  const workerPath = resolve(cwd, opts.out ?? 'worker.yaml');
  await writeFile(workerPath, yaml, 'utf8');
  return { workerPath, yaml };
}
